# Generated by Django 5.2.16 on 2026-09-18 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Name (in Block Letters)')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=15, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('institution', models.CharField(max_length=250, verbose_name='Name of Institution')),
                ('designation', models.CharField(max_length=150, verbose_name='Designation')),
                ('department', models.CharField(max_length=150, verbose_name='Department')),
                ('category', models.CharField(choices=[('Teaching Staff', 'Teaching Staff'), ('Non-Teaching Staff', 'Non-Teaching Staff')], default='Teaching Staff', max_length=30, verbose_name='Category')),
                ('address', models.TextField(verbose_name='Permanent Address')),
                ('pincode', models.CharField(max_length=10, verbose_name='Pin Code')),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='Thiruvananthapuram', max_length=50, verbose_name='District')),
                ('membership_type', models.CharField(choices=[('Annual Membership', 'Annual Membership'), ('Life Membership', 'Life Membership')], default='Annual Membership', max_length=30, verbose_name='Type of Membership')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/', verbose_name='Applicant Photo')),
                ('declaration', models.BooleanField(default=True, verbose_name='Agreed to Declaration')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('membership_fee', models.CharField(blank=True, default='', max_length=100, verbose_name='Membership Fee Received')),
                ('receipt_no', models.CharField(blank=True, default='', max_length=100, verbose_name='Receipt No')),
                ('membership_no', models.CharField(blank=True, default='', max_length=100, verbose_name='Membership No')),
                ('approved_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Approved By')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Office Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Application Date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Application',
                'verbose_name_plural': 'Membership Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
