# Generated by Django 5.2.16 on 2026-09-18 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/%Y/%m/', verbose_name='Payment Screenshot'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Payment Rejected')], default='Pending Verification', max_length=30, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Transaction ID / UTR'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='wing',
            field=models.CharField(choices=[('Arts and sciences', 'Arts and sciences'), ('Teacher Education', 'Teacher Education'), ('Law colleges', 'Law colleges'), ('Engineering Colleges', 'Engineering Colleges'), ('Health and Allied Sciences', 'Health and Allied Sciences'), ('Principal', 'Principal'), ('Administrative Staffs', 'Administrative Staffs')], default='Arts and sciences', max_length=50, verbose_name='Wing'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='membership_fee',
            field=models.CharField(default='₹ 200', max_length=100, verbose_name='Membership Fee'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved / Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Application Status'),
        ),
    ]
