# Generated by Django 5.2.16 on 2026-09-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershipapplication_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='other_wing',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Other Wing (Specify)'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='wing',
            field=models.CharField(choices=[('Arts and sciences', 'Arts and sciences'), ('Teacher Education', 'Teacher Education'), ('Law colleges', 'Law colleges'), ('Engineering Colleges', 'Engineering Colleges'), ('Health and Allied Sciences', 'Health and Allied Sciences'), ('Principal', 'Principal'), ('Administrative Staffs', 'Administrative Staffs'), ('Other', 'Other (Please Specify)')], default='Arts and sciences', max_length=50, verbose_name='Wing'),
        ),
    ]
