# Generated by Django 5.2.16 on 2026-09-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_membershipapplication_other_wing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified Date'),
        ),
    ]
