# Generated by Django 5.2.16 on 2026-09-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_membershipapplication_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='category',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Teaching', 'Teaching'), ('Non teaching', 'Non teaching')], default='Teaching', max_length=30, verbose_name='Category'),
        ),
    ]
