# Generated by Django 5.2.16 on 2026-09-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_membershipapplication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='payment_screenshot',
            field=models.TextField(blank=True, null=True, verbose_name='Base64 Payment Screenshot'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Base64 Photo'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Transaction ID / UTR No'),
        ),
    ]
